### ISSUE TITLE
Recipe Review: csv-files-spaces-column-names

### ISSUE THREAD

**Issue by hdulay** [startreedata/pinot-recipes#12]
Currently Reviewing This Recipe.

https://github.com/startreedata/pinot-recipes/tree/main/recipes/csv-files-spaces-column-names

**Comment by hdulay** [comment]
Adding table causes this error:


2024/02/22 16:32:33.142 INFO [AddTableCommand] [main] Executing command: AddTable -tableConfigFile /config/table.json -offlineTableConfigFile null -realtimeTableConfigFile null -schemaFile /config/schema.json -controllerProtocol http -controllerHost pinot-controller-csv -controllerPort 9000 -user null -password [hidden] -exec
2024/02/22 16:32:34.947 INFO [AddTableCommand] [main] {"code":400,"error":"Invalid TableConfigs: crimes"}

**Comment by hdulay** [comment]
@matthewhelmke 

PR https://github.com/startreedata/pinot-recipes/pull/13

**Comment by matthewhelmke** [comment]
@hdulay #13 is approved. Do you have the ability to merge? If not, I'll do it.

**Comment by matthewhelmke** [comment]
Editorial review PR: https://github.com/startreedata/pinot-recipes/pull/15

**Comment by matthewhelmke** [comment]
This is complete! :)
