### ISSUE TITLE
Recipe Reivew: debezium-cdc

### ISSUE THREAD

**Issue by hdulay** [startreedata/pinot-recipes#14]
This recipe is under review

https://github.com/startreedata/pinot-recipes/tree/main/recipes/debezium-cdc

**Comment by hdulay** [comment]
@matthewhelmke - Need to add a top level docker-compose to be included within all the recipes. I'm going to update the CSV recipe to include this compose file.

**Comment by hdulay** [comment]
@matthewhelmke - this is done

**Comment by matthewhelmke** [comment]
Looks good to me! We can mark this issue closed.
